# Generated by Django 4.0.1 on 2022-01-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pearlApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pearls',
            old_name='description',
            new_name='list',
        ),
    ]
